Revert "Auto-click show more buttons (#109)"
alejandro5042/azdo-userscripts pull request #112
Opened 2020-09-23 17:55 UTC by xhuff

This reverts commit 2fd2cc460a714acd12cf8d6b866f711e1fa55917.

I've been recently having my New column forcibly expand itself even after I've closed it multiple times following an AzDO Boards page refresh. This hangs up my Boards refresh for up to a couple of minutes at a time. Additionally, this massively balloons (>4x) the number of filter options to look through, since those options are populated by the union of all currently visible work items.
 
While this seems like it could be helpful if these columns are in use, my squad only uses the New state for things outside our current iteration, so I always want the column collapsed when I'm using the Boards view. Revert for now, since this is having negative impact.

2020-09-23 21:12 UTC, alejandro5042 commented
Thanks for bringing this up! What if instead of removing the feature, we simply avoid pressing "Show More" if the New column is open? Alternatively, we could add a feature flag for this... the Review Board userscript has many user-configurable feature flags. The AzDO userscript (which predates the RB userscript) traditionally doesn't but can start to.

What do you think? Personally, I think adding a feature flag is an easy way forward. It also solves another use case: If your backlog is huge or your connection is slow, maybe you don't want it to auto-expand, anyways.

Here is an example of adding a feature flag: https://github.com/ni/reviewboard-userscripts/blob/master/src/ni-reviewboard.user.js#L25

Then, after adding a config option (`eus` is avaiable in the azdo userscript), you can modify the selectors in lines 275 of the azdo-userscript to look for it

```js
eus.globalSession.onEveryNew(document, 'body.my-feature-flag a[role="button"].see-more-items', async showMoreButton => {
```

I suggest adding the feature flag only to the Kanban board version, since that's the only one that affects you.

2020-09-23 21:13 UTC, alejandro5042 requested changes
See my earlier comment.

2020-09-23 21:25 UTC, xhuff commented
> What if instead of removing the feature, we simply avoid pressing "Show More" if the New column is open?

I think I'd want the _alternate_ to be true. If New is collapsed, don't click it.

> Alternatively, we could add a feature flag for this... the Review Board userscript has many user-configurable feature flags. The AzDO userscript (which predates the RB userscript) traditionally doesn't but can start to.

That would also serve my needs, but FWIW, this script seems to have exceeded its initial purpose. It's title is 'AzDO Pull Request Improvements', but it's not affecting AzDO areas beyond PRs. Should it's title be changed if this scope growth is desired?

I can look into adding the flag, unless you think you could whip it up before me 😄

2020-09-23 21:46 UTC, xhuff commented
So, being very new to JS/UI, here's what I'm thinking you're saying.

Add this to the top:

`    eus.registerCssClassConfig(document.body, 'Select theme', 'theme', 'ni-light', {
      'ni-expand-kanban-columns': 'Try to always expand the New and Closed columns',
      'ni-dont-expand-kanban-columns': 'Do not expand the New and Closed columns automatically (default behavior)',
    });`

And modify the Kanban board `eus.globalSession.onEveryNew` section to use `body.ni-expand-kanban-columns`?

I think I may be missing how the option is actually presented to the user?

2020-09-29 13:31 UTC, alejandro5042 commented
Yep basically that's it. Except pick different strings than "theme":

```
    eus.registerCssClassConfig(document.body, 'Select theme', 'theme', 'ni-light', {
// first param: the element to put the CSS element on
// second param: the description to show in the config dialog box
// third param: the name of the key to store in local storage with this config value
// fourth param: the default value (see keys in the following dictionary)
```

> I think I may be missing how the option is actually presented to the user?

It'll show up in your userscript manager. If you click TamperMonkey, for example, you'll see an option for "Select theme" (or whatever you renamed it to) and that'll launch a dialog box to set the setting.

2020-09-29 14:18 UTC, closed without merging

2020-09-29 14:19 UTC, xhuff commented
I filed this issue instead of trying to fix myself: https://github.com/alejandro5042/azdo-userscripts/issues/122