NI: Add button to launch binary git diff protocol handler
alejandro5042/azdo-userscripts pull request #136
Opened 2020-12-17 21:10 UTC by humberto-garza

# Justification

It is not an easy task to review binary files in AzDO.

We want to be able to launch a custom protocol handler that can diff NI Binaries from AzDO PRs directly.

# Implementation

- Add a `Launch NI Binary Git Diff` button to binary files with these extensions: 'vi', 'vim', 'vit', 'ctt', 'ctl'
- For now, only support Windows
- Add a `?` button that displays a message with some help -> We still don't know where we will document the instructions to install the protocol handler, so in the future, we can potentially add a link here.

# Testing

On Windows:

Dark Theme
![image](https://user-images.githubusercontent.com/8660999/102543732-5a970800-4079-11eb-99d6-800452952142.png)

Light Theme
![image](https://user-images.githubusercontent.com/8660999/102543873-8d410080-4079-11eb-82b7-3d9dda4f0e3a.png)

On Linux
![image](https://user-images.githubusercontent.com/8660999/102544103-ee68d400-4079-11eb-86ab-40a9564222bf.png)

2021-01-14 23:42 UTC, alejandro5042 requested changes

2021-01-14 23:42 UTC, alejandro5042 commented on src/azdo-pr-dashboard.user.js
> +          addNiBinaryDiffButton();
Please make it "LabVIEW" or "NI".

i.e. we don't camel case our brand name: NI is better than Ni.

2021-01-14 23:42 UTC, alejandro5042 commented on src/azdo-pr-dashboard.user.js
> +        argin-right: 2px;
Is `argin-right` a typo?

2021-01-14 23:42 UTC, alejandro5042 commented on src/azdo-pr-dashboard.user.js
> +        const protocolHandlerAddress = `NIBinary.GitDiff:${filePath} ${prevCommitId} ${nextCommitId}`;
Uh noesss.... We have spaces in our URL scheme :sad:

Typically URLs don't have spaces. Is this scheme still in development where we can recommend using commas (at minimum) or perhaps some sort of query string?

2021-01-14 23:42 UTC, alejandro5042 commented on src/azdo-pr-dashboard.user.js
> +        const protocolHandlerAddress = `NIBinary.GitDiff:${filePath} ${prevCommitId} ${nextCommitId}`;
Typically prev/next terminology for Git diffing is "source/target" or even "before/after" or "original/modified".

2021-01-14 23:42 UTC, alejandro5042 commented on src/azdo-pr-dashboard.user.js
> +        helpDialog.toggle();
The userscript -- because it uses [easy-userscript](https://gist.githubusercontent.com/alejandro5042/af2ee5b0ad92b271cd2c71615a05da2c/raw/67b7203dfbc48f08ebddfc8327c92b2df28a3c4c/easy-userscripts.js?v=72#sha384-OgOM7UvZHxtPUmZoGbYhsgkLPuRj9SFTpO+LqbnaBzLDQaXmYlosSywfsljzjhCI) -- has access to the [SweetAlert2](https://sweetalert2.github.io/) dialog library :)

Search for "swal" in [this file](https://github.com/ni/reviewboard-userscripts/blob/master/src/ni-reviewboard.user.js) for how to use in this userscript.

---

This will be better than rolling our own dialog or notification code here.

2021-01-14 23:44 UTC, alejandro5042 commented
- We should also add a note in the README about this new feature
- We should rev the minor version too
- We should advise users in the "dialog" where to download the URI handler, and if no link exists yet, state that its a preview feature and talk to XYZ to get it

2021-01-14 23:45 UTC, alejandro5042 commented
Minor: What do you think of the button wording, `Compare with LabVIEW`? Seeing if there's something clearer.

2021-01-26 22:49 UTC, humberto-garza commented on src/azdo-pr-dashboard.user.js
> +          addNiBinaryDiffButton();
It was a requirement that it was named "NI" instead of "LabVIEW" because in the future it might be used for other products too.

2021-01-26 22:49 UTC, humberto-garza commented on src/azdo-pr-dashboard.user.js
> +        argin-right: 2px;
Great catch!

2021-01-26 22:49 UTC, humberto-garza commented on src/azdo-pr-dashboard.user.js
> +        const protocolHandlerAddress = `NIBinary.GitDiff:${filePath} ${prevCommitId} ${nextCommitId}`;
I talked to the client and he said it is okay to use commas

2021-01-26 22:50 UTC, humberto-garza commented on src/azdo-pr-dashboard.user.js
> +        const protocolHandlerAddress = `NIBinary.GitDiff:${filePath} ${prevCommitId} ${nextCommitId}`;
I like this. 
Updated to use "before/after" instead

2021-01-26 22:50 UTC, humberto-garza commented on src/azdo-pr-dashboard.user.js
> +        helpDialog.toggle();
Awesome! 
I am using SweetAlert and I have updated the PR description accordingly

2021-01-26 22:51 UTC, humberto-garza commented
@alejandro5042 

> * We should also add a note in the README about this new feature

Done!

> * We should rev the minor version too

Done! 

> * We should advise users in the "dialog" where to download the URI handler, and if no link exists yet, state that its a preview feature and talk to XYZ to get it

I updated the dialog to contact me for now.
Also, I am not sure about posting internal links in this tool.

2021-02-10 20:58 UTC, alejandro5042 approved these changes

2021-02-10 20:59 UTC, merged