Update help text for NI Binary Git Diff
alejandro5042/azdo-userscripts pull request #148
Opened 2021-03-18 15:16 UTC by shastriUF

The current help text says to contact Humberto. We now have instructions in the wiki, so I'm updating the help text to point to the wiki (without including the internal-only link). I tested that searching for that string in the NI Azure DevOps wiki will return the instructions we need as the first result.

2021-03-18 16:05 UTC, humberto-garza approved these changes

2021-03-24 16:27 UTC, alejandro5042 requested changes
Thank you for this change 👍 

Please follow the steps for a PR as posted by the welcome bot above: https://github.com/alejandro5042/azdo-userscripts/blob/master/CONTRIBUTING.md#testing-before-a-pr

Specifically, you need to bump the patch version in the userscript.

2021-03-24 16:27 UTC, alejandro5042 commented on src/azdo-pr-dashboard.user.js
> +          text: 'You need to install the "NIBinary.GitDiff.reg" Protocol Handler first. To get it, please talk to Humberto Garza, or search for "Launch NI Binary Git Diff" in the Azure DevOps NI Wiki
Swal (our dialog library) has an option for an HTML dialog. I suggest we add a `<a target="_blank" href="LINK_TO_WIKI">TEXT</a>` link. A link is more useful than a search term; and our links are now permalinks (with the ID in the wiki page).

Tip: Change `text:` to `html:`. For more docs: https://sweetalert2.github.io/#configuration

2021-03-24 16:28 UTC, alejandro5042 commented on src/azdo-pr-dashboard.user.js
> +          text: 'You need to install the "NIBinary.GitDiff.reg" Protocol Handler first. To get it, please talk to Humberto Garza, or search for "Launch NI Binary Git Diff" in the Azure DevOps NI Wiki
Please test this too 😄 I'm assuming it works the way it says it does.

2021-03-24 18:00 UTC, humberto-garza commented on src/azdo-pr-dashboard.user.js
> +          text: 'You need to install the "NIBinary.GitDiff.reg" Protocol Handler first. To get it, please talk to Humberto Garza, or search for "Launch NI Binary Git Diff" in the Azure DevOps NI Wiki
Are we okay with sharing the actual permalink here?

2021-03-24 23:15 UTC, alejandro5042 commented on src/azdo-pr-dashboard.user.js
> +          text: 'You need to install the "NIBinary.GitDiff.reg" Protocol Handler first. To get it, please talk to Humberto Garza, or search for "Launch NI Binary Git Diff" in the Azure DevOps NI Wiki
I'm OK with it. We already share a _little_ bit about our AzDO instance (e.g. it is at `ni.visualstudio.com`), our process (e.g. `niconfig` and intermittent failure file paths) and besides _everything_ is behind authentication. The links don't reveal any IP. Besides, the permalink can be stripped to only contain the ID number and not even the page title:

e.g. https://dev.azure.com/ni/DevCentral/_wiki/wikis/AppCentral.wiki/16924

2022-11-30 01:51 UTC, alejandro5042 approved these changes

2022-11-30 01:56 UTC, merged