Rewrite trophies to work in "new" PR experience
alejandro5042/azdo-userscripts pull request #206
Opened 2022-12-13 22:30 UTC by jerone

Part of #95.

* Added existing trophies: 
  * Milestone trophy
  * Fish trophy. 
	  * Added extra condition that PR ID needs to be at least 3 numbers.
* Added new trophies:
  * First PR
  * 1337 leetspeak
  * Night owl

![image](https://user-images.githubusercontent.com/55841/207458115-ffd1193f-b8a8-423a-983f-0fdad61ab94d.png)

2022-12-20 15:59 UTC, alejandro5042 requested changes
Wonderful! Thank you so much for taking a stab at fixing this feature. Left some comments for us to discuss. Excited to get a fix for this in!

2022-12-20 15:59 UTC, alejandro5042 commented on src/azdo-pr-dashboard.user.js
> +        const firstPrTrophyMessage = $('<div>').addClass('bolt-table-cell-content').text(`🥇 ${prAuthor} first pull request`);
While this is the author's first PR, it's also the first PR, ever, right? Nobody else would ever get the "author's first PR" trophy, am I understanding the way that PR IDs work correctly?

2022-12-20 15:59 UTC, alejandro5042 commented on src/azdo-pr-dashboard.user.js
> +      // Who need sleep when you have coffee? PR created between 2 and 5 am.
If the PR creation date is in UTC, or if the author is in another time zone (e.g. you are in USA and author is in China), how does this code handle those scenarios?

2022-12-20 16:53 UTC, jerone commented on src/azdo-pr-dashboard.user.js
> +      if (prId === 1337) {
In my opinion this would look weird. 1337 is very specific. `13378` for example looks nothing at all like leet.
Just like 1000, 2000, etc, this number is very specific.

2022-12-20 16:56 UTC, jerone commented on src/azdo-pr-dashboard.user.js
> +        const firstPrTrophyMessage = $('<div>').addClass('bolt-table-cell-content').text(`🥇 ${prAuthor} first pull request`);
Pull request identifiers are unique per project within in your organization. Meaning that you could get this trophy once per project.

2022-12-20 16:59 UTC, jerone commented on src/azdo-pr-dashboard.user.js
> +      // Who need sleep when you have coffee? PR created between 2 and 5 am.
I have no idea what timezones the PR creation date is in. You can see the returned format on line [1194](https://github.com/alejandro5042/azdo-userscripts/pull/206/files#diff-87bc55158e53df27f65971bb6f16be4e67caed3023839334bf37b768d60640c7R1194).

2023-01-21 09:40 UTC, jerone commented
@alejandro5042 I replied to your comments. Anything else I can do?

2023-01-25 06:25 UTC, alejandro5042 requested changes
Make sure you update the version on line 4, following semver. So if this is a feature update, then update the middle number; if a bug fix, then the last number; if breaking change (which I don't think this would qualify for), then the first number.

2023-01-25 06:25 UTC, alejandro5042 commented on src/azdo-pr-dashboard.user.js
> +      if (prId === 1337) {
OK fair enough!

2023-01-25 06:25 UTC, alejandro5042 commented on src/azdo-pr-dashboard.user.js
> +        const firstPrTrophyMessage = $('<div>').addClass('bolt-table-cell-content').text(`🥇 ${prAuthor} first pull request`);
I like your 2nd suggestion: "author is first"

2023-01-25 06:25 UTC, alejandro5042 commented on src/azdo-pr-dashboard.user.js
> +      // Who need sleep when you have coffee? PR created between 2 and 5 am.
I'd prefer we excluded this one until we have a better solution.

Where I work (NI), we have developers in maybe half the time zones all around the world. This trophy would most certainly be wrong for most people that live far away from what I presume we're comparing to, which is UTC time zone.

I'm happy to add this in if we can somehow find the user's time zone... at this point, I'm at a loss at how to do that. Open to suggestions.

2023-01-25 06:27 UTC, alejandro5042 commented
Hey @jerone! Sorry for the delay... holidays and vacations had me AFK for several weeks and I spent the last few catching up and starting the year with new work initiatives. But I'm back! Happy to get your changes in once we're all good with the code.

2023-01-25 16:43 UTC, jerone commented
@alejandro5042 I applied your feedback and increased semver minor version.

2023-01-27 18:44 UTC, alejandro5042 approved these changes

2023-01-27 18:49 UTC, merged

2023-01-27 18:49 UTC, alejandro5042 commented
Thanks @jerone! Merged in.